spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/asaxiy
    username: asaxiy
    password: asaxiy
  jpa:
    show-sql: true
    open-in-view: false
server:
  port: 8080